<?php /** @var \Magento\Catalog\Block\Product\View $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<?php /** @TODO: only logged in customers must be able to make a request. Show login form on button click */ ?>
<button class="action primary" data-mage-init='{"andriiShkrebtiiRegularCustomerButton": {
            "productId": "<?= $escaper->escapeJs($block->getProduct()->getId()) ?>"
    }}'>
    <span><?= $escaper->escapeHtml(__('Participate in the program')) ?></span>
</button>
